site_name: Khalti Services Documentation
nav:
  - Introduction: index.md
  - Service Status Check : 
      - State List: Servicescodes/statecode.md
      - DLR: Servicescodes/dlr.md
      - Service Balance Check: Servicescodes/balance_check.md
      - Service LookUp API: Servicescodes/lookup.md
      - Bulk Service Lookup: Servicescodes/bulkservice.md
  - Mobile TopUp:
        - Khalti Topup: Khaltitopup/khaltitopup.md
        - NTC: MobileTopup/nepal_telecom.md
        - Ncell: MobileTopup/ncell.md
  - Data Packs:
      - Ncell DataPacks: datapacks/NcellProduct.md
      - NTC DataPacks: datapacks/ntcProduct.md

      
  - Electricity:
      - Nea v1 : Electricity/nea.md
      - Nea v2 : Electricity/nea-v2.md
  - Khanepani: 
      - Community Khanepani: Khanepani/khanepani.md
      - Kukl:
          - Counter : Khanepani/Kukl/counter.md 
          - Kukl Details: Khanepani/Kukl/Kukl-Details.md
          - Service Charge: servicecharge/service-charge.md
          - KUKL Payment: Khanepani/Kukl/Kukl-payment.md

  - TV :
    - Nettv:  TV/nettv.md
    - SimTV: TV/simtv.md
    - Max Tv: TV/maxtv.md
    - Dishhome: Internet/dishhome.md
    - Prabhu Tv: TV/Prabhutv.md
    - P & G Network: TV/p&g.md
    - Jagriti Cable: TV/jagrititv.md
    - Times: TV/times.md

  - Internet:
    - Worldlink: Internet/worldlink.md
    - Vianet: Internet/vianet-new.md
    - Adsl: Internet/adsl.md
    - NTFTTH : Internet/ntftth.md
    - Dishhome: Internet/dishhome.md
    - Subisu: Internet/subisu.md
    # - Classic Tech: Internet/classictech.md
    - Wifi Nepal: Internet/wifi-nepal.md
    - Broadlink: Internet/broadlink.md
    - Times Internet: Internet/timesinternet.md
    - Arrownet: Internet/arrownet.md
    - Virtual Network: Internet/Virtual-network.md
    - Web Network: Internet/web-network.md
    - Royal Network: Internet/royal-network.md
    - Techminds: Internet/hashcnet/v2.md
    - East Link : Internet/eastlink.md
    - Metrolink: Internet/metrolink.md
    - Infonet Communication: Internet/infonet.md
    - Pokhara Internet: Internet/pokhara-internet.md
    - Nijgad Cable: Internet/nijgad_cable.md
    - Net Max: Internet/netmax.md
    - Dolfin Internet: Internet/dolfin-internet.md
    - HashCNet V1: Internet/hashcnet/v1.md
    - HashCNet V2: Internet/hashcnet/v2.md
    - Fibertel Fibernet: Internet/Fibertel.md
    - Rapid Unique Net: Internet/rapidapi.md
    - GRS Internet: Internet/grs-internet.md
    - Infonet Technology: Internet/infonet.md
    - Merosoft: Internet/merosoft.md
    - Konnect: Internet/konnect.md
    - Kriti Darshan: Internet/kriti-darshan.md
    - Chitrawan Unique Net: Internet/chitrawan.md
    - Airlink Communication: Internet/airlink.md
    - 3G Vision: Internet/3g-vision.md
    - First Link: Internet/first-link.md
    - Sky Broadband: Internet/sky-broadband.md
    

  - Insurance: 
      - Non life Insurances:
          - Arhant Non-Life Insurances: Insurance/Arhant Insurance/non_life.md 
          - Prudential Insurance: Insurance/prudential/prudential.md
          - Neco Insurance:  Insurance/neco_insurance.md
          - Sagarmatha Lumbini Insurance: Insurance/sagarmatha_insurance.md
          - Nepal Non Life Insurance: Insurance/nepal_non_life.md

      
      
      - Life Insurances:
        - Metlife Insurance: Insurance/metlife.md 
        - Arhant Life Insurance : Insurance/Arhant Insurance/life.md 
        - Surya Life Insurance: Insurance/surya/Suryalife.md
        - Sanima Insurance: Insurance/Reliance Insurance/reliance_insurance.md    
        - Sun Life Insurance: Insurance/Sunlife/sunlife.md
        - Rastriya Beema Sansthan: Insurance/rastriyabeema.md
        - Surya Jyoti Loan Repayment: Insurance/suryajoytiloan.md
        - Reliable Insurance: Insurance/Reliable_life.md
        - Citizen Life Insurance: Insurance/Citizen/citizen.md
        - Surya Life Insurance First Payment:  Insurance/surya/surya_life_insurance.md
        - IME General Insurance: Insurance/ime/ime_general.md
        - Insur Tech Life Insurance: Insurance/insur-tech-life.md
        - Nepal Life Insurance: Insurance/Nepal/nepal_Life_Insurace.md
        - Himalayan Life Insurance: Insurance/himalaya-insurance.md
        - National Life Insurance: Insurance/national-life-insurance.md

      - Loan Repayment : 
        - Arhant Loan Repayment: Insurance/Arhant Insurance/Life Loan Repayment/arhant-loan-repayment.md  
        - Insur Tech: Insurance/insur-tech-loan.md

  - EMI:
    - Maw EMI: EMI/maw/maw.md
    - Synergy EMI: EMI/synergy/synergy.md
    -  Code Himalayan Emi: EMI/code-himalayan-emi/code-himalayan-emi.md


  - Community Electricity:
    - Himchuli Electricity: Electricity/Himchuli.md
    - Watermark Electricity: Electricity/watermark.md
    - Dreamer Electricity: Electricity/dreamer.md
    - Softlab Electricity: Electricity/softlab.md
    - BPC Electricity: Electricity/bpc.md

  - Cable Car: Cable Car/cablecar.md

  - Antivirus:
      - Kaspersky Antivirus: antivirus/kaspersky.md
      - Eset Antivirus: antivirus/eset.md
      - K7 Antivirus: antivirus/k7.md
      - Wardwiz Antivirus: antivirus/wardwiz.md
      - Mcafee Antivirus: antivirus/mcafee.md

  - Meroshare & Demat :
      - Counter: CDSC/dp-counter.md
      - Details: CDSC/details.md
      - Demat Service Charge: servicecharge/service-charge.md
      - Payment: CDSC/payment.md 

  - Waste Management:
    - Waste Management: waste/waste-mgmt.md
    
  - Ride:
      - CABTM: Ride/cabtm.md
      - Tottle: Ride/tootle.md

  - Bluebook: bluebook/bluebook.md
  - PSTN (Landline): PSTN/landline.md
  - Bus: 
    - Routes: Bus/route.md
    - Search: Bus/search.md
    - Seat: Bus/seat.md
    - Book Bus: Bus/bus-booking.md
    - Add info: Bus/add-info.md
    - Payment: Bus/payment.md
    - Download Ticket: Bus/ticket-download.md
  - Social Security Fund: ssf/ssf.md
  - Central Zoo: central-zoo/zoo.md
  - Gov Payment:
    - eChalan: gov-payment/echalan.md
    - Gov Payment: gov-payment/gov-payment.md

  - Flight:
    - Sector : flight/sector.md 
    - Search Flight: flight/search.md
    - Book Flight: flight/book.md
    - Add info: flight/addinfo.md
    - Issue Ticket: flight/issue.md
    - Cancel Flight: flight/cancel.md
    - Ticket Download: flight/ticketdownload.md
    - Flight LookUp: flight/flight-lookup.md
    - Flight Status: flight/flightstatus.md
    - Flight Info: flight/info.md  
    - Flight FAQ: flight/faq.md


  - SIP:
    - Kumari SIP: 
        - SIP info: sip/kumari-sip/sip-info.md
        - BOID validation: sip/kumari-sip/boid-validate.md
        - SIP Registration: sip/kumari-sip/sip-registration.md
        - Lumspum Payment: sip/kumari-sip/lumpsum-payment.md
        - SIP :
          - SIP Details : sip/kumari-sip/sip/sip-payment-details.md
          - SIP Payment: sip/kumari-sip/sip/sip-payment-payment.md

  - World Cup:
      - Dishhome Go coupon: Worldcup/Dishhome/dishhome-go.md
      - Dishhome Fifa Recharge : Worldcup/Dishhome/dishhome-fifa-recharge.md
      - Nettv Coupon: Worldcup/nettv/nettvcine.md
      - Nettv Fifa Recharge: Worldcup/nettv/nettv-api.md
      - Max TV: Worldcup/maxtv/maxtv.md

  - Test Data:
      - Test Data: test-data/testdata.md
  
  - Rc Card: Rc card/rccard.md
  - NTC eSim : eSim/ntcesim.md
  - Changelog: Servicescodes/changelog.md
  - FAQ's: Servicescodes/faq.md



theme:
  name: material
  custom_dir: overrides
  favicon: "https://cdn.nayathegana.com/media/2025/07/13/23471783407643cb921f718ed30726b9.png"
  icon:
    logo: "img/khalti_logo"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - style/custom.css
  - style/extra.css
docs_dir: content 
site_dir: docs

copyright: "Copyright &copy; 2025 IME Khalti  Limited"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/khalti"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/KhaltiOfficial"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/khalti-digital-wallet"
    - icon: "fontawesome/brands/facebook"
      link: "https://facebook.com/khaltiofficial"
    - icon: "fontawesome/brands/instagram"
      link: "https://www.instagram.com/khaltiofficial/"

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

# Uncomment and install any necessary plugins if needed
# plugins:
#   - search
#   - social
